Improves the service descriptor file
usabilla/api-php pull request #4
Opened 2017-04-06 20:57 UTC by rodrigorigotti

Improves the service descriptor file so a faulty call is corrected and several common structutes are moved to a separate model.

2017-04-07 08:28 UTC, tzengerink approved these changes

2017-04-07 12:30 UTC, lcobucci commented
@rodrigorigotti I honestly have no context here so I'm unable to give any review

2017-04-07 12:57 UTC, rodrigorigotti commented
@lcobucci this is the PHP SDK for our Public API. There's a descriptor file which states what are the endpoints of the API and the parameters for each one of them.

There was a bug in the `WebsiteCampaignResultItems` model so the customers couldn't use the `GetWebsiteCampaignResults` command. I made the fix and also removed some of the redundancies in the description file so it's smaller and easier to understand.

2017-04-10 08:58 UTC, rdohms requested changes
Please split the commits, its not clear what the bug was and what the reformatting is.

2017-04-10 09:37 UTC, rdohms requested changes

2017-04-10 09:37 UTC, rdohms commented on src/Usabilla/API/Description/UsabillaDescription.php
>                      ],
does this not lose the item definition?

2017-04-10 09:39 UTC, rodrigorigotti commented on src/Usabilla/API/Description/UsabillaDescription.php
>                      ],
This model already existed, it wasn't just being used here.

2017-04-10 15:57 UTC, rdohms commented on src/Usabilla/API/Description/UsabillaDescription.php
>                      ],
yes but the definitions you deleted had a `'items'` key you that is now gone?

2017-04-10 15:57 UTC, rdohms commented on src/Usabilla/API/Description/UsabillaDescription.php
>                      ],
nevermind, github was confusing me.

2017-04-10 15:57 UTC, rdohms approved these changes

2017-04-10 17:41 UTC, merged