Add Get campaigns and getCampaignFeedback
usabilla/api-php pull request #6
Opened 2017-12-21 12:31 UTC by Rifinio

@usabilla/sdk 
This PR adds the new Campaign for apps endpoints, one to retrieve campaigns and the other for retrieving the results of a given campaign.

2017-12-21 13:34 UTC, tzengerink requested changes

2017-12-21 13:34 UTC, tzengerink commented on examples/single_page_with_id.php
> +
This line can be removed and the last line should have a `newline` at the end.

2017-12-21 13:34 UTC, tzengerink commented on README.MD
> +You can use the command line to retrieve results from the api using scripts found in the [example folder](examples/):
`API` instead of `api`.

2017-12-21 14:33 UTC, TomPaeta approved these changes

2017-12-21 16:09 UTC, tzengerink approved these changes

2017-12-21 16:31 UTC, rodrigorigotti requested changes
Please fix the commit message as well - either something in the lines of "Add commands to get app campaigns and app campaign results" or "Add GetAppCampaigns and GetAppCampaignResults"; the way it currently is is kind of mixed

2017-12-21 16:31 UTC, rodrigorigotti commented on src/Usabilla/API/Description/UsabillaDescription.php
> +                        'id' => [ '$ref' => 'NonMandatoryIdParam' ],
The id is mandatory, right? Then it needs to be `MandatoryIdParam`

2017-12-21 16:31 UTC, rodrigorigotti commented on src/Usabilla/API/Description/UsabillaDescription.php
> +                'GetAppCampaignResultItems' => [
Please let's keep the naming convention, should be `GetAppCampaignResults` (since the one for feedback items is `GetWebsiteCampaignResults`)

2017-12-22 10:08 UTC, rodrigorigotti requested changes

2017-12-22 10:08 UTC, rodrigorigotti commented on examples/single_page_with_id.php
> +list($commandName, $id, $accessKey, $secretKey, $id) = array_slice($argv, 1);
The id is mapped from the second argument, not the fourth, please remove the last one (also executing this scripts gives an `Undefined offset` notice)

2017-12-22 10:40 UTC, rodrigorigotti approved these changes

2017-12-22 11:06 UTC, merged